# Generated by Django 4.2.2 on 2023-06-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='integerproductattribute',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='textproductattribute',
            name='attribute_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='int',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.integerproductattribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.textproductattribute'),
        ),
        migrations.AlterField(
            model_name='category',
            name='perent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='atr',
        ),
        migrations.AlterField(
            model_name='product',
            name='stocke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='atr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
    ]
