# Generated by Django 4.2.2 on 2023-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_remove_category_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stocke',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='int',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.integerproductattribute'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.textproductattribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='atr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
