# Generated by Django 4.2.2 on 2023-06-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_comment_product_dislikes_dislike_commentlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='attribute',
            name='perent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.attribute'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='atr',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='atr',
            field=models.ManyToManyField(blank=True, default=0, related_name='atributes', to='product.attribute'),
        ),
    ]
