# Generated by Django 4.2.2 on 2023-06-28 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_remove_product_dislikes_remove_product_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_product', through='product.DisLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_products', through='product.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integerproductattribute',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
