# Generated by Django 4.2.2 on 2023-06-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_dislikes_product_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='textproductattribute',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='int',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='text',
        ),
        migrations.RemoveField(
            model_name='product',
            name='atr',
        ),
        migrations.DeleteModel(
            name='IntegerProductAttribute',
        ),
        migrations.DeleteModel(
            name='TextProductAttribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute'),
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, default=None, related_name='atributes', to='product.productattribute'),
        ),
    ]
