# Generated by Django 4.2.2 on 2023-06-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
